# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(684, 327)
        Dialog.setMinimumSize(QtCore.QSize(684, 327))
        Dialog.setMaximumSize(QtCore.QSize(684, 327))
        Dialog.setWindowOpacity(1.0)
        self.Title = QtWidgets.QLabel(Dialog)
        self.Title.setGeometry(QtCore.QRect(0, 0, 681, 41))
        font = QtGui.QFont()
        font.setFamily("a_Simpler3D")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Title.setAutoFillBackground(False)
        self.Title.setTextFormat(QtCore.Qt.AutoText)
        self.Title.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Title.setObjectName("Title")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 661, 241))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(370, 10, 47, 13))
        self.label_3.setObjectName("label_3")
        self.Message = QtWidgets.QTextEdit(self.groupBox)
        self.Message.setEnabled(True)
        self.Message.setGeometry(QtCore.QRect(370, 30, 281, 201))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Message.setFont(font)
        self.Message.setAcceptDrops(False)
        self.Message.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.Message.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Message.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Message.setReadOnly(False)
        self.Message.setOverwriteMode(False)
        self.Message.setObjectName("Message")
        self.filechoose2 = QtWidgets.QPushButton(self.groupBox)
        self.filechoose2.setGeometry(QtCore.QRect(330, 90, 31, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.filechoose2.setFont(font)
        self.filechoose2.setObjectName("filechoose2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_2.setObjectName("label_2")
        self.directory2 = QtWidgets.QTextEdit(self.groupBox)
        self.directory2.setEnabled(True)
        self.directory2.setGeometry(QtCore.QRect(20, 90, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.directory2.setFont(font)
        self.directory2.setAcceptDrops(False)
        self.directory2.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.directory2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.directory2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.directory2.setReadOnly(True)
        self.directory2.setObjectName("directory2")
        self.send_code = QtWidgets.QPushButton(self.groupBox)
        self.send_code.setGeometry(QtCore.QRect(120, 40, 61, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.send_code.setFont(font)
        self.send_code.setObjectName("send_code")
        self.phonenumber = QtWidgets.QTextEdit(self.groupBox)
        self.phonenumber.setEnabled(True)
        self.phonenumber.setGeometry(QtCore.QRect(20, 40, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.phonenumber.setFont(font)
        self.phonenumber.setAcceptDrops(False)
        self.phonenumber.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.phonenumber.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.phonenumber.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.phonenumber.setReadOnly(False)
        self.phonenumber.setObjectName("phonenumber")
        self.label_1 = QtWidgets.QLabel(self.groupBox)
        self.label_1.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_1.setObjectName("label_1")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 61, 16))
        self.label_4.setObjectName("label_4")
        self.Interval = QtWidgets.QTextEdit(self.groupBox)
        self.Interval.setEnabled(True)
        self.Interval.setGeometry(QtCore.QRect(20, 190, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Interval.setFont(font)
        self.Interval.setAcceptDrops(False)
        self.Interval.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.Interval.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Interval.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Interval.setReadOnly(False)
        self.Interval.setObjectName("Interval")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.label_5.setObjectName("label_5")
        self.directory4 = QtWidgets.QTextEdit(self.groupBox)
        self.directory4.setEnabled(True)
        self.directory4.setGeometry(QtCore.QRect(20, 140, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.directory4.setFont(font)
        self.directory4.setAcceptDrops(False)
        self.directory4.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.directory4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.directory4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.directory4.setReadOnly(True)
        self.directory4.setObjectName("directory4")
        self.filechoose3 = QtWidgets.QPushButton(self.groupBox)
        self.filechoose3.setGeometry(QtCore.QRect(330, 140, 31, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.filechoose3.setFont(font)
        self.filechoose3.setObjectName("filechoose3")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(90, 170, 81, 16))
        self.label_6.setObjectName("label_6")
        self.repeats = QtWidgets.QTextEdit(self.groupBox)
        self.repeats.setEnabled(True)
        self.repeats.setGeometry(QtCore.QRect(100, 190, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.repeats.setFont(font)
        self.repeats.setAcceptDrops(False)
        self.repeats.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.repeats.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.repeats.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.repeats.setReadOnly(False)
        self.repeats.setObjectName("repeats")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(190, 20, 71, 16))
        self.label_7.setObjectName("label_7")
        self.code = QtWidgets.QTextEdit(self.groupBox)
        self.code.setEnabled(True)
        self.code.setGeometry(QtCore.QRect(200, 40, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.code.setFont(font)
        self.code.setAcceptDrops(False)
        self.code.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.code.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.code.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.code.setReadOnly(False)
        self.code.setObjectName("code")
        self.verify = QtWidgets.QPushButton(self.groupBox)
        self.verify.setGeometry(QtCore.QRect(300, 40, 61, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.verify.setFont(font)
        self.verify.setObjectName("verify")
        self.start = QtWidgets.QPushButton(Dialog)
        self.start.setGeometry(QtCore.QRect(540, 290, 131, 31))
        font = QtGui.QFont()
        font.setFamily("VALORANT")
        font.setPointSize(12)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.load = QtWidgets.QPushButton(Dialog)
        self.load.setGeometry(QtCore.QRect(400, 290, 131, 31))
        font = QtGui.QFont()
        font.setFamily("VALORANT")
        font.setPointSize(12)
        self.load.setFont(font)
        self.load.setObjectName("load")
        self.status = QtWidgets.QLineEdit(Dialog)
        self.status.setGeometry(QtCore.QRect(10, 290, 381, 31))
        self.status.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.status.setAcceptDrops(False)
        self.status.setReadOnly(True)
        self.status.setObjectName("status")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ultra Super Cool TeleGram Spammer 2000"))
        self.Title.setText(_translate("Dialog", "USCTGSPAMER 2000"))
        self.groupBox.setTitle(_translate("Dialog", "Input"))
        self.label_3.setText(_translate("Dialog", "Message"))
        self.Message.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter the message here...</p></body></html>"))
        self.filechoose2.setText(_translate("Dialog", "..."))
        self.label_2.setText(_translate("Dialog", "Target groups"))
        self.directory2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Choose file...</p></body></html>"))
        self.send_code.setText(_translate("Dialog", "Send code"))
        self.phonenumber.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">88005553535</p></body></html>"))
        self.label_1.setText(_translate("Dialog", "Phone number"))
        self.label_4.setText(_translate("Dialog", "Interval(s)"))
        self.Interval.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">15</p></body></html>"))
        self.label_5.setText(_translate("Dialog", "Log output"))
        self.directory4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Choose folder...</p></body></html>"))
        self.filechoose3.setText(_translate("Dialog", "..."))
        self.label_6.setText(_translate("Dialog", "№ of repeats"))
        self.repeats.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))
        self.label_7.setText(_translate("Dialog", "Code"))
        self.code.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">598265</p></body></html>"))
        self.verify.setText(_translate("Dialog", "Verify"))
        self.start.setText(_translate("Dialog", "Start"))
        self.load.setText(_translate("Dialog", "Load"))
        self.status.setText(_translate("Dialog", "Loading file D:\\Games\\Dota 2.exe..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
